# Generated by Django 5.1.7 on 2025-03-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_remove_subject_grade_alter_subject_name_grade_and_more'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='subjects',
            field=models.ManyToManyField(to='subjects.grade'),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
