# Generated by Django 5.1.7 on 2025-05-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
