# Generated by Django 5.1.7 on 2025-03-11 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_requirement'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='requirements',
        ),
        migrations.AddField(
            model_name='requirement',
            name='max_grade',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=6, help_text='Maximum acceptable grade for this subject'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirement', to='programs.program'),
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('program', 'subject')},
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='subject',
        ),
        migrations.AddField(
            model_name='requirement',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
