# Generated by Django 5.1.7 on 2025-03-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='English', max_length=100, unique=True),
        ),
    ]
